language: node_js
node_js:
  - 12

dist: trusty
sudo: false

cache: yarn

script: yarn run generate

after_script:
  - yarn install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
