language: node_js
node_js:
  - 12

dist: trusty
sudo: false

cache: yarn

script:
  - yarn run generate
  - yarn add --dev coveralls
  - yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
